# ===================================================================
# Spring Boot configuration.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
    level:
        ROOT: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update

# ===================================================================
# Application specific properties
# ===================================================================
application:
  upload:
    saveFolder: ./files